#!/bin/bash
set -euo pipefail

# Prepare the Linux Raw Gadget test substrate for the *running* kernel.
#
# This script is intentionally host/runtime preparation, not semantic package
# resolution. It builds and installs dummy_hcd only when the running kernel
# does not already provide a loadable module, and it refuses to force-load a
# module built for another kernel.

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
: "${OOREXX_VUSB_DUMMY_HCD_SOURCE_DIR:=$(CDPATH= cd -- "$ROOT/.." && pwd)/dummy-hcd}"
: "${OOREXX_VUSB_DUMMY_HCD_MODULE:=$OOREXX_VUSB_DUMMY_HCD_SOURCE_DIR/dummy_hcd.ko}"
: "${OOREXX_VUSB_RAW_GADGET_PATH:=/dev/raw-gadget}"
: "${OOREXX_VUSB_UDC_DEVICE:=dummy_udc.0}"

fail() { echo "RAW GADGET PREP: FAIL: $*" >&2; exit 1; }
note() { echo "RAW GADGET PREP: $*"; }

INSTALL_BUILD_DEPS=0
INTERNAL_ROOT_HANDOFF=0

# Parse the private sudo handoff before public arguments.  dev6 parsed the
# public option first, so the --as-root marker generated by the script itself
# was rejected as an unknown argument.
if [ "${1:-}" = "--as-root" ]; then
  INTERNAL_ROOT_HANDOFF=1
  [ "$#" -eq 6 ] || fail "internal root handoff argument mismatch"
  shift
  OOREXX_VUSB_DUMMY_HCD_SOURCE_DIR=$1
  OOREXX_VUSB_DUMMY_HCD_MODULE=$2
  OOREXX_VUSB_RAW_GADGET_PATH=$3
  OOREXX_VUSB_UDC_DEVICE=$4
  INSTALL_BUILD_DEPS=$5
  shift 5
else
  case "${1:-}" in
    "") ;;
    --install-build-deps) INSTALL_BUILD_DEPS=1; shift ;;
    *) echo "RAW GADGET PREP: FAIL: unknown argument: $1" >&2; exit 2 ;;
  esac
  [ "$#" -eq 0 ] || { echo "RAW GADGET PREP: FAIL: unexpected extra argument: $1" >&2; exit 2; }
fi

# Preserve the source path and option across sudo rather than depending on
# sudo's environment policy.
if [ "$(id -u)" -ne 0 ]; then
  exec sudo -- "$0" --as-root \
      "$OOREXX_VUSB_DUMMY_HCD_SOURCE_DIR" \
      "$OOREXX_VUSB_DUMMY_HCD_MODULE" \
      "$OOREXX_VUSB_RAW_GADGET_PATH" \
      "$OOREXX_VUSB_UDC_DEVICE" \
      "$INSTALL_BUILD_DEPS"
fi

[ "$INTERNAL_ROOT_HANDOFF" -eq 0 ] || note "root handoff accepted"

kernel=$(uname -r)
build="/lib/modules/$kernel/build"
source_link="/lib/modules/$kernel/source"
module_dir="/lib/modules/$kernel/extra/oorexx-vusb"
installed_module="$module_dir/dummy_hcd.ko"

note "running kernel: $kernel"

install_build_deps() {
  [ "$INSTALL_BUILD_DEPS" -eq 1 ] || return 1
  command -v zypper >/dev/null 2>&1 || fail "--install-build-deps requested but zypper is unavailable"
  note "installing openSUSE kernel build prerequisites"
  zypper --non-interactive install kernel-default-devel kernel-devel kernel-source gcc make
}

if [ ! -f "$build/Makefile" ]; then
  install_build_deps || fail "matching kernel build tree is absent: $build/Makefile; install kernel-default-devel kernel-devel kernel-source gcc make for $kernel, then rerun (or use --install-build-deps)"
fi

command -v make >/dev/null 2>&1 || { install_build_deps || fail "make is unavailable; install gcc make"; }
command -v modprobe >/dev/null 2>&1 || fail "modprobe unavailable"
command -v depmod >/dev/null 2>&1 || fail "depmod unavailable"

# raw_gadget is expected to be the in-tree module on the qualified openSUSE
# kernel. Loading it here also creates /dev/raw-gadget on normal udev setups.
if ! grep -q '^raw_gadget ' /proc/modules 2>/dev/null; then
  note "loading raw_gadget"
  modprobe raw_gadget || fail "modprobe raw_gadget failed for $kernel"
else
  note "raw_gadget already loaded"
fi

# If the running kernel already supplies dummy_hcd, use it. No out-of-tree
# build is needed in that case.
if grep -q '^dummy_hcd ' /proc/modules 2>/dev/null; then
  note "dummy_hcd already loaded"
elif modprobe dummy_hcd 2>/dev/null; then
  note "loaded installed dummy_hcd"
else
  srcdir=$OOREXX_VUSB_DUMMY_HCD_SOURCE_DIR
  mkdir -p "$srcdir"

  # Prefer source shipped for the running kernel.  This matters after a
  # reinstall or kernel update: retaining an older dummy_hcd.c beside the test
  # tree must not silently become source authority for a newer kernel API.
  kernel_dummy=''
  for candidate in \
      "$source_link/drivers/usb/gadget/udc/dummy_hcd.c" \
      "$build/../../../linux-${kernel%-default}/drivers/usb/gadget/udc/dummy_hcd.c"; do
    if [ -f "$candidate" ]; then
      kernel_dummy=$(readlink -f "$candidate")
      break
    fi
  done

  if [ -n "$kernel_dummy" ]; then
    if [ ! -f "$srcdir/dummy_hcd.c" ] || ! cmp -s "$kernel_dummy" "$srcdir/dummy_hcd.c"; then
      note "refreshing dummy_hcd.c from running-kernel source: $kernel_dummy"
      cp -f "$kernel_dummy" "$srcdir/dummy_hcd.c"
    else
      note "dummy_hcd.c already matches running-kernel source"
    fi
  else
    [ -f "$srcdir/dummy_hcd.c" ] || fail "dummy_hcd.c not found in running-kernel source tree or $srcdir"
    note "running-kernel dummy_hcd.c source not found; using retained source: $srcdir/dummy_hcd.c"
  fi

  cat > "$srcdir/Makefile" <<'MAKEEOF'
obj-m += dummy_hcd.o
MAKEEOF

  reusable=0
  if [ -f "$OOREXX_VUSB_DUMMY_HCD_MODULE" ] && command -v modinfo >/dev/null 2>&1; then
    vermagic=$(modinfo -F vermagic "$OOREXX_VUSB_DUMMY_HCD_MODULE" 2>/dev/null || true)
    case "$vermagic" in
      "$kernel"*) reusable=1; note "existing dummy_hcd.ko vermagic matches $kernel" ;;
      '') note "existing dummy_hcd.ko has no readable vermagic; rebuilding" ;;
      *) note "existing dummy_hcd.ko is for '$vermagic'; rebuilding for $kernel" ;;
    esac
  fi

  if [ "$reusable" -ne 1 ]; then
    note "building dummy_hcd against $build"
    make -C "$build" M="$srcdir" clean
    make -C "$build" M="$srcdir" modules
  fi

  [ -f "$OOREXX_VUSB_DUMMY_HCD_MODULE" ] || fail "build did not produce $OOREXX_VUSB_DUMMY_HCD_MODULE"
  if command -v modinfo >/dev/null 2>&1; then
    vermagic=$(modinfo -F vermagic "$OOREXX_VUSB_DUMMY_HCD_MODULE" 2>/dev/null || true)
    case "$vermagic" in
      "$kernel"*) note "built dummy_hcd vermagic OK: $vermagic" ;;
      *) fail "built dummy_hcd vermagic '$vermagic' does not match running kernel '$kernel'" ;;
    esac
  fi

  note "installing dummy_hcd for running kernel: $installed_module"
  install -d -m 0755 "$module_dir"
  install -m 0644 "$OOREXX_VUSB_DUMMY_HCD_MODULE" "$installed_module"
  depmod -a "$kernel"
  modprobe dummy_hcd || fail "installed dummy_hcd did not load"
  note "dummy_hcd installed and loaded"
fi

for _ in $(seq 1 50); do
  [ -c "$OOREXX_VUSB_RAW_GADGET_PATH" ] && [ -e "/sys/class/udc/$OOREXX_VUSB_UDC_DEVICE" ] && break
  sleep 0.1
done

[ -c "$OOREXX_VUSB_RAW_GADGET_PATH" ] || fail "$OOREXX_VUSB_RAW_GADGET_PATH was not created"
[ -e "/sys/class/udc/$OOREXX_VUSB_UDC_DEVICE" ] || fail "UDC $OOREXX_VUSB_UDC_DEVICE did not appear"

note "raw-gadget node ready: $(ls -l "$OOREXX_VUSB_RAW_GADGET_PATH")"
note "UDC ready: $OOREXX_VUSB_UDC_DEVICE"
note "PASS running-kernel Raw Gadget substrate"
