#pragma once
#include "xtp/xtp_route.hpp"
#include "xtp/xtp_transport.hpp"
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace xtp {

struct MultipathOptions {
    size_t max_paths = 2;
    size_t chunk_bytes = 16u * 1024u;
    uint32_t generation = 0; // 0 -> derive from persistent path generation
    uint64_t transfer_id = 0; // 0 -> generated by library
    bool replay_over_survivor = true;
    SendOptions send;
};

struct MultipathPathResult {
    Route route;
    size_t assigned_chunks = 0;
    size_t delivered_chunks = 0;
    size_t replayed_chunks = 0;
    bool failed = false;
    std::string error;
};

struct MultipathSendResult {
    uint64_t transfer_id = 0;
    uint32_t generation = 0;
    size_t logical_bytes = 0;
    size_t chunk_count = 0;
    size_t failovers = 0;
    std::vector<MultipathPathResult> paths;
};

struct MultipathReceiveResult {
    uint64_t transfer_id = 0;
    uint32_t generation = 0;
    size_t chunks = 0;
    size_t logical_bytes = 0;
    std::vector<uint8_t> logical;
};

// Sender stripes chunks over the ordered route set.  When an assigned path
// fails, the failed chunk is replayed over the next surviving path using the
// same transfer/generation/chunk identity.  Applications see one transfer.
MultipathSendResult send_multipath(const std::vector<Route>& routes,
                                   const std::vector<uint8_t>& logical,
                                   const MultipathOptions& options = {});

// Persistent receiver for one logical multipath endpoint.  It owns one XTP
// Listener per route and reassembles XMP1 chunks independent of arrival path.
class MultipathListener {
public:
    explicit MultipathListener(const std::vector<Route>& routes,
                               const ListenOptions& listen_options = {});
    ~MultipathListener();
    MultipathListener(MultipathListener&&) noexcept;
    MultipathListener& operator=(MultipathListener&&) noexcept;
    MultipathListener(const MultipathListener&) = delete;
    MultipathListener& operator=(const MultipathListener&) = delete;

    MultipathReceiveResult receive();
    void close();
private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

} // namespace xtp
