known = x2c("3011020101600c0201030404636e3d61800178")
encoded = .LdapWireCodec~encodeBindRequest(1, "cn=a", "x")
ignore = .LdapIdentityTest~equal(c2x(known), c2x(encoded), "bind known-answer BER")
msg = .LdapWireCodec~decodeMessage(encoded)
ignore = .LdapIdentityTest~assert(msg["ok"], "decode LDAPMessage")
ignore = .LdapIdentityTest~equal(1, msg["messageId"], "message id")
ignore = .LdapIdentityTest~equal(.LdapWireCodec~OP_BIND_REQUEST, msg["opTag"], "bind tag")
bind = .LdapWireCodec~decodeBindRequest(msg["opValue"])
ignore = .LdapIdentityTest~assert(bind["ok"], "decode bind")
ignore = .LdapIdentityTest~equal(3, bind["version"], "ldap version")
ignore = .LdapIdentityTest~equal("cn=a", bind["name"], "bind dn")
ignore = .LdapIdentityTest~equal("x", bind["credential"], "credential")
search = .LdapWireCodec~encodeSearchRequest(2, "dc=example,dc=org", "SUB", "(uid=alice)", .array~of("uid", "cn"))
sm = .LdapWireCodec~decodeMessage(search)
sr = .LdapWireCodec~decodeSearchRequest(sm["opValue"])
ignore = .LdapIdentityTest~assert(sr["ok"], "search decode")
ignore = .LdapIdentityTest~equal("dc=example,dc=org", sr["baseDn"], "search base")
ignore = .LdapIdentityTest~equal("SUB", sr["scope"], "scope")
ignore = .LdapIdentityTest~equal("(uid=alice)", sr["filterText"], "filter")
ignore = .LdapIdentityTest~equal(2, sr["attributes"]~items, "requested attributes")
mods = .array~new
mods~append(.LdapModification~new("REPLACE", "uid", .array~of("alice2")))
modify = .LdapWireCodec~encodeModifyRequest(3, "uid=alice,dc=example,dc=org", mods)
mm = .LdapWireCodec~decodeMessage(modify)
ignore = .LdapIdentityTest~equal(.LdapWireCodec~OP_MODIFY_REQUEST, mm["opTag"], "modify tag")
mr = .LdapWireCodec~decodeModifyRequest(mm["opValue"])
ignore = .LdapIdentityTest~assert(mr["ok"], "modify decode")
ignore = .LdapIdentityTest~equal("uid=alice,dc=example,dc=org", mr["dn"], "modify dn")
ignore = .LdapIdentityTest~equal(1, mr["modifications"]~items, "modify count")
ignore = .LdapIdentityTest~equal("REPLACE", mr["modifications"][1]~operation, "modify op")
ignore = .LdapIdentityTest~equal("uid", mr["modifications"][1]~attributeName, "modify attr")
ignore = .LdapIdentityTest~equal("alice2", mr["modifications"][1]~values[1], "modify value")
/* LDAPMessage controls remain framing, not semantic authority. */
syncControl = .LdapSyncCodec~requestControl("REFRESH_ONLY", .nil, .false, .true)
controlled = .LdapWireCodec~encodeSearchRequest(4, "dc=example,dc=org", "SUB", "(uid=alice)", .array~of("uid"), 0, 0, .false, .array~of(syncControl))
cm = .LdapWireCodec~decodeMessage(controlled)
ignore = .LdapIdentityTest~assert(cm["ok"], "controlled message decode")
ignore = .LdapIdentityTest~equal(1, cm["controls"]~items, "one control")
ignore = .LdapIdentityTest~equal(.LdapSyncBuild~REQUEST_OID, cm["controls"][1]~controlType, "Sync request OID")
ignore = .LdapIdentityTest~assert(cm["controls"][1]~criticality, "Sync request critical")
syncDecoded = .LdapSyncCodec~decodeRequestControl(cm["controls"][1])
ignore = .LdapIdentityTest~assert(syncDecoded["ok"], "Sync request value decode")
ignore = .LdapIdentityTest~equal("REFRESH_ONLY", syncDecoded["mode"], "Sync refreshOnly mode")

saslBytes = '00'x || "uid=alice,dc=example,dc=org" || '00'x || "secret"
saslMessage = .LdapWireCodec~encodeSaslBindRequest(5, "PLAIN", saslBytes)
sm = .LdapWireCodec~decodeMessage(saslMessage)
sb = .LdapWireCodec~decodeBindRequest(sm["opValue"])
ignore = .LdapIdentityTest~assert(sb["ok"], "SASL Bind decode")
ignore = .LdapIdentityTest~equal("SASL", sb["authType"], "SASL bind auth type")
ignore = .LdapIdentityTest~equal("PLAIN", sb["mechanism"], "SASL mechanism")
ignore = .LdapIdentityTest~equal(c2x(saslBytes), c2x(sb["credential"]), "SASL credentials binary preserved")

startTls = .LdapWireCodec~encodeExtendedRequest(6, .LdapTlsBuild~STARTTLS_OID)
em = .LdapWireCodec~decodeMessage(startTls)
er = .LdapWireCodec~decodeExtendedRequest(em["opValue"])
ignore = .LdapIdentityTest~assert(er["ok"], "StartTLS ExtendedRequest decode")
ignore = .LdapIdentityTest~equal(.LdapTlsBuild~STARTTLS_OID, er["requestName"], "StartTLS OID")
ignore = .LdapIdentityTest~assert(er["requestValue"] == .nil, "StartTLS request value absent")

uuidText = "00112233-4455-4677-8899-aabbccddeeff"
uuidBytes = .LdapSyncCodec~uuidBytes(uuidText)
ignore = .LdapIdentityTest~equal(16, uuidBytes~length, "Sync UUID binary length")
ignore = .LdapIdentityTest~equal(uuidText, .LdapSyncCodec~uuidText(uuidBytes), "Sync UUID binary/text round trip")
stateControl = .LdapSyncCodec~stateControl("MODIFY", uuidBytes)
stateDecoded = .LdapSyncCodec~decodeStateControl(stateControl)
ignore = .LdapIdentityTest~assert(stateDecoded["ok"], "Sync State decode")
ignore = .LdapIdentityTest~equal("MODIFY", stateDecoded["state"], "Sync modify state")
badStateValue = .LdapBer~sequence(.LdapBer~enumerated(2) || .LdapBer~octet(uuidBytes) || .LdapBer~octet("cookie") || .LdapBer~boolean(.true))
badState = .LdapControl~new(.LdapSyncBuild~STATE_OID, .false, badStateValue)
badDecoded = .LdapSyncCodec~decodeStateControl(badState)
ignore = .LdapIdentityTest~assert(\badDecoded["ok"], "Sync State trailing bytes rejected")
ignore = .LdapIdentityTest~equal("LDAP_SYNC_STATE_TRAILING_BYTES", badDecoded["code"], "Sync State trailing-byte code")

say "LDAP BER: OK"
::requires "tests/TestSupport.cls"
::requires "src/LdapSync.cls"
::requires "src/LdapTls.cls"
