-- Generated by sql_torture_generator.py
-- target size: 0.001 MB | seed: 42 | foreign keys: off

-- ==========================================================================
-- SCHEMA: 5 tables, deliberately under-indexed (see unhelpful queries below)
-- ==========================================================================

CREATE TABLE customers (
    customer_id   INTEGER PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    city          VARCHAR(50)  NOT NULL,
    signup_date   DATE         NOT NULL,
    loyalty_tier  VARCHAR(20)  NOT NULL
);

CREATE TABLE employees (
    employee_id   INTEGER PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    hire_date     DATE         NOT NULL,
    manager_id    INTEGER      NULL,
    department    VARCHAR(50)  NOT NULL
);

CREATE TABLE products (
    product_id    INTEGER PRIMARY KEY,
    product_name  VARCHAR(100) NOT NULL,
    category      VARCHAR(50)  NOT NULL,
    unit_price    DECIMAL(10,2) NOT NULL,
    stock_qty     INTEGER      NOT NULL
);

CREATE TABLE orders (
    order_id      INTEGER PRIMARY KEY,
    customer_id   INTEGER NOT NULL,
    employee_id   INTEGER NOT NULL,
    order_date    DATE    NOT NULL,
    status        VARCHAR(20) NOT NULL
);

CREATE TABLE order_items (
    order_item_id INTEGER PRIMARY KEY,
    order_id      INTEGER NOT NULL,
    product_id    INTEGER NOT NULL,
    quantity      INTEGER NOT NULL,
    unit_price    DECIMAL(10,2) NOT NULL
);


-- 4 customers
INSERT INTO customers (customer_id, full_name, email, city, signup_date, loyalty_tier) VALUES
(1, 'Linda Smith', 'linda.smith1@example.com', 'Leeds', '2021-09-30', 'SILVER'),
(2, 'William Patel', 'william.patel2@example.com', 'Manchester', '2025-02-11', 'BRONZE'),
(3, 'Declan Johnson', 'declan.johnson3@example.com', 'Glasgow', '2020-01-19', 'SILVER'),
(4, 'Joseph Kowalski', 'joseph.kowalski4@example.com', 'Glasgow', '2025-04-17', 'SILVER');

-- 5 employees
INSERT INTO employees (employee_id, full_name, hire_date, manager_id, department) VALUES
(1, 'Noor Robertson', '2019-12-11', NULL, 'Logistics'),
(2, 'Sarah Haddad', '2015-02-23', NULL, 'Support'),
(3, 'Declan MacLeod', '2021-03-26', NULL, 'Support'),
(4, 'Susan Okafor', '2022-07-20', NULL, 'Warehouse'),
(5, 'Jennifer Stewart', '2017-03-03', NULL, 'HR');

-- 5 products
INSERT INTO products (product_id, product_name, category, unit_price, stock_qty) VALUES
(1, 'Foldable Chair', 'Stationery', 135.19, 355),
(2, 'Budget Charger', 'Fitness', 65.9, 3100),
(3, 'Deluxe Tent', 'Toys', 415.37, 2962),
(4, 'Classic Backpack', 'Kitchenware', 26.72, 1866),
(5, 'Modular Monitor', 'Kitchenware', 428.23, 827);

-- orders + order_items, grown to fill target size


-- ==========================================================================
-- UNHELPFUL QUERIES
-- Every one of these is a legitimate question answered the worst way
-- the schema and SQL allow. Use them to make a planner cry.
-- ==========================================================================

-- [1] The Kitchen Sink
-- Five-way join, zero filters, ORDER BY six columns using mixed ascending/descending sorts nobody asked for.
SELECT c.full_name, c.city, o.order_id, o.order_date, p.product_name,
       oi.quantity, (oi.quantity * oi.unit_price) AS line_total,
       e.full_name AS handled_by
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
JOIN products p ON p.product_id = oi.product_id
JOIN employees e ON e.employee_id = o.employee_id
ORDER BY c.city, c.full_name, o.order_date DESC, p.category,
         p.product_name, oi.quantity DESC;

-- [2] Correlated Subqueries Instead Of A Join
-- Every column is its own round trip. Classic N+1-in-SQL.
SELECT o.order_id,
       (SELECT c.full_name FROM customers c
         WHERE c.customer_id = o.customer_id) AS customer_name,
       (SELECT SUM(oi.quantity * oi.unit_price) FROM order_items oi
         WHERE oi.order_id = o.order_id) AS order_total,
       (SELECT COUNT(*) FROM order_items oi2
         WHERE oi2.order_id = o.order_id) AS item_count
FROM orders o
ORDER BY order_total DESC;

-- [3] Function-Wrapped WHERE, Wildcards Both Ends
-- UPPER()/LOWER()/SUBSTR() on every row guarantees no index could ever help, even if one existed.
SELECT * FROM customers
WHERE UPPER(city) LIKE '%ON%'
  AND LOWER(SUBSTR(email,1,1)) BETWEEN 'a' AND 'm';

-- [4] Old-Style Comma Join With Bolted-On DISTINCT
-- No explicit JOIN syntax, implicit cross product cleaned up after the fact with DISTINCT.
SELECT DISTINCT c.customer_id, c.full_name, c.city, p.category
FROM customers c, orders o, order_items oi, products p
WHERE o.customer_id = c.customer_id
  AND oi.order_id = o.order_id
  AND oi.product_id = p.product_id;

-- [5] Three-Level Self-Join Org Chart
-- Employee, manager, and manager's manager, purely for the pleasure of three LEFT JOINs on one table.
SELECT e1.full_name AS employee, e2.full_name AS manager,
       e3.full_name AS director
FROM employees e1
LEFT JOIN employees e2 ON e2.employee_id = e1.manager_id
LEFT JOIN employees e3 ON e3.employee_id = e2.manager_id
ORDER BY director, manager, employee;

-- [6] HAVING Threshold Recomputed Per Group
-- The 'average category revenue' should be one constant. Instead it's a derived subquery re-evaluated against every group.
SELECT p.category, COUNT(*) AS items_sold,
       SUM(oi.quantity * oi.unit_price) AS revenue
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
GROUP BY p.category
HAVING SUM(oi.quantity * oi.unit_price) > (
    SELECT AVG(sub.cat_revenue) FROM (
        SELECT p2.category, SUM(oi2.quantity * oi2.unit_price) AS cat_revenue
        FROM order_items oi2 JOIN products p2 ON p2.product_id = oi2.product_id
        GROUP BY p2.category
    ) sub
)
ORDER BY revenue DESC;

-- [7] Anti-Join Via LEFT JOIN / IS NULL
-- Finds customers with no non-cancelled order, the long way round instead of NOT EXISTS.
SELECT c.customer_id, c.full_name
FROM customers c
LEFT JOIN orders o
  ON o.customer_id = c.customer_id AND o.status <> 'CANCELLED'
WHERE o.order_id IS NULL
ORDER BY c.full_name;

-- [8] UNION Where UNION ALL (Or Just OR) Would Do
-- Forces a full dedup/sort across three overlapping row sets.
SELECT * FROM orders WHERE status = 'PENDING'
UNION
SELECT * FROM orders WHERE status = 'SHIPPED'
UNION
SELECT * FROM orders
WHERE customer_id IN (SELECT customer_id FROM customers WHERE loyalty_tier = 'GOLD')
ORDER BY order_date;

-- [9] Four-Deep Nested IN Subqueries
-- Each level re-scans instead of joining once.
SELECT * FROM products
WHERE product_id IN (
    SELECT product_id FROM order_items WHERE order_id IN (
        SELECT order_id FROM orders WHERE customer_id IN (
            SELECT customer_id FROM customers WHERE city IN (
                SELECT city FROM customers WHERE loyalty_tier = 'PLATINUM'
            )
        )
    )
);

-- [10] CASE-Expression Sort Plus String-Concat Sort Key
-- Sorts by a computed CASE, then by a concatenated string nobody indexed because you can't.
SELECT o.order_id, o.status, c.full_name, o.order_date
FROM orders o JOIN customers c ON c.customer_id = o.customer_id
ORDER BY
  CASE o.status
    WHEN 'CANCELLED' THEN 3
    WHEN 'RETURNED' THEN 2
    ELSE 1
  END,
  c.city || '-' || c.full_name,
  o.order_date DESC;

-- [11] The Accidental Cross Join
-- customers and employees share no relationship whatsoever. This joins everyone to everyone and hopes WHERE saves it.
SELECT c.full_name, e.full_name, e.department
FROM customers c, employees e
WHERE c.city = 'Glasgow'
ORDER BY e.department;

-- [12] SELECT-List Full Of Aggregate Subqueries
-- Three independent aggregate subqueries per customer row instead of one GROUP BY.
SELECT c.customer_id, c.full_name,
  (SELECT COUNT(*) FROM orders o WHERE o.customer_id = c.customer_id) AS order_count,
  (SELECT COALESCE(SUM(oi.quantity*oi.unit_price),0)
     FROM orders o JOIN order_items oi ON oi.order_id = o.order_id
     WHERE o.customer_id = c.customer_id) AS lifetime_value,
  (SELECT MAX(o.order_date) FROM orders o WHERE o.customer_id = c.customer_id) AS last_order
FROM customers c
ORDER BY lifetime_value DESC;
