#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
: "${REXX_BIN:=rexx}"
: "${BRANCH_DAY_SRC:?set BRANCH_DAY_SRC}"
: "${BRANCH_CASH_SRC:?set BRANCH_CASH_SRC}"
: "${BRANCH_CASH_SERVICE_SRC:?set BRANCH_CASH_SERVICE_SRC}"
: "${TELLER_TILL_SRC:?set TELLER_TILL_SRC}"
: "${TELLER_CASH_SRC:?set TELLER_CASH_SRC}"
: "${TELLER_CASH_SERVICE_SRC:?set TELLER_CASH_SERVICE_SRC}"
: "${EXTERNAL_CASH_SRC:?set EXTERNAL_CASH_SRC}"
: "${EXTERNAL_CASH_SERVICE_SRC:?set EXTERNAL_CASH_SERVICE_SRC}"
: "${EXTERNAL_BRANCH_ADAPTER_SRC:?set EXTERNAL_BRANCH_ADAPTER_SRC}"
export REXX_PATH="$HERE/src:$HERE/runtime:$HERE/tests:$BRANCH_DAY_SRC:$BRANCH_CASH_SRC:$BRANCH_CASH_SERVICE_SRC:$TELLER_TILL_SRC:$TELLER_CASH_SRC:$TELLER_CASH_SERVICE_SRC:$EXTERNAL_CASH_SRC:$EXTERNAL_CASH_SERVICE_SRC:$EXTERNAL_BRANCH_ADAPTER_SRC${REXX_PATH:+:$REXX_PATH}"
for t in "$HERE"/tests/test_*.rex; do echo "== $(basename "$t") =="; "$REXX_BIN" "$t"; done
