book=.AJITestSupport~contractBook(.array~of(.AJITestSupport~contractVersion("AJI-CONTRACT-PI-GB/1","PI","GB","2026-01-01","")))
a=.AllJapanInsuranceAuthority~new(.nil,book)
channel=.AJITestSupport~actor("DIRECT",.AllJapanInsuranceBuild~ROLE_DISTRIBUTION)
uw=.AJITestSupport~actorRoles("UW",.array~of(.AllJapanInsuranceBuild~ROLE_UNDERWRITER,.AllJapanInsuranceBuild~ROLE_RATE_OVERRIDE))
pa=.AJITestSupport~actor("PA",.AllJapanInsuranceBuild~ROLE_POLICY)
ci=.AJITestSupport~actor("CI",.AllJapanInsuranceBuild~ROLE_CLAIMS_INTAKE)
s=.AllJapanInsuranceRiskSubmission~new("S-PI-1","PI","REL-PI","RISK-PI","GB","2026-08-28")
ignored=.AJITestSupport~must(a~submitRisk(channel,s),"submit")
d=.AllJapanInsuranceUnderwritingDecision~new("D-PI-1","S-PI-1","PI","ACCEPT","AJI-PRODUCT-PI/0.1","UW","2026-08-28T10:00:00","EVID")
ignored=.AJITestSupport~must(a~recordDecision(uw,d),"decision")
q=.AllJapanInsuranceQuote~new("Q-PI-1","D-PI-1","S-PI-1","PI",50000,"GBP","2026-09-02T23:59:59","2026-08-28T10:01:00","","","MANUAL_OVERRIDE","legacy lifecycle fixture")
ignored=.AJITestSupport~must(a~issueQuote(uw,q),"quote")
p=.AllJapanInsurancePolicy~new("P-PI-1","Q-PI-1","REL-PI","PI","RISK-PI","2026-09-01","2027-09-01","2026-08-29T10:00:00")
ignored=.AJITestSupport~must(a~bindPolicy(pa,p),"bind")
c=.AllJapanInsuranceClaim~new("C-PI-OLD","P-PI-1","REL-PI","2026-08-31","2026-09-02T08:00:00","LOSS-OLD")
r=a~openClaim(ci,c)
ignored=.AJITestSupport~assert(\r~ok,"pre-inception loss denied")
ignored=.AJITestSupport~assert(r~code="LOSS_OUTSIDE_COVERAGE","coverage period enforced")
say "PASS claim loss date must fall inside policy coverage"
::requires "TestSupport.cls"
