using Alchemy.OoRexx;
using System.Reflection;
using System.Reflection.Emit;
public interface IAlchemyMarker {}
public interface ISpeaker { string Speak(); }
public class BaseThing {}
public class Thing:BaseThing,IAlchemyMarker {
 sealed record BehaviourState(long Generation, Func<string> Speak);
 BehaviourState behaviour = new(0, () => "C#-INITIAL");
 public long BehaviourGeneration => Volatile.Read(ref behaviour).Generation;
 public string Speak()=>Volatile.Read(ref behaviour).Speak();
 public long ReplaceCSharp(string value){while(true){var old=Volatile.Read(ref behaviour);var next=new BehaviourState(old.Generation+1,()=>value);if(ReferenceEquals(Interlocked.CompareExchange(ref behaviour,next,old),old))return next.Generation;}}
 public long InstallRexxBehaviour(){if(RexxPeer is null) throw new InvalidOperationException("RexxPeer not installed");while(true){var old=Volatile.Read(ref behaviour);var next=new BehaviourState(old.Generation+1,()=>{using var r=RexxPeer.Send("SPEAK");return r.ToString();});if(ReferenceEquals(Interlocked.CompareExchange(ref behaviour,next,old),old))return next.Generation;}}
 public (long Generation,string Value) InvokeSnapshot(){var snapshot=Volatile.Read(ref behaviour);return(snapshot.Generation,snapshot.Speak());}
 public long InstallBlockingCSharp(string value,ManualResetEventSlim entered,ManualResetEventSlim release){while(true){var old=Volatile.Read(ref behaviour);var next=new BehaviourState(old.Generation+1,()=>{entered.Set();if(!release.Wait(TimeSpan.FromSeconds(10)))throw new TimeoutException("concurrent behaviour release timeout");return value;});if(ReferenceEquals(Interlocked.CompareExchange(ref behaviour,next,old),old))return next.Generation;}}
 public string Ping()=>"pong-from-clr"; public Thing Self()=>this; public string Explode()=>throw new InvalidOperationException("alchemy-clr-boom");
 public object Echo(object x)=>x; public long FortyTwo()=>42L; public double Pi()=>3.25; public RexxObject? RexxPeer { get; set; }
 public Thing NestedSelf(){if(RexxPeer is null) throw new InvalidOperationException("RexxPeer not installed");using var echoed=RexxPeer.SendSparse("ECHOOBJECT",RexxPeer);using var same=RexxPeer.SendSparse("SAMEOBJECT",echoed);if(same.ToString()!="1") throw new InvalidOperationException("nested Rexx identity lost");return this;}
 public string Slots(object? a,object? b,object? c,object? d)=>string.Join("|",new[]{Tag(a),Tag(b),Tag(c),Tag(d)});
 static string Tag(object? v)=>ReferenceEquals(v,AlchemyOmitted.Value)?"OMITTED":v is null?"NIL":v is string s&&s.Length==0?"EMPTY":"VALUE:"+v;
}
public static class TypedSpeakerFactory {
 static readonly Type SpeakerType = BuildType();
 static Type BuildType(){var an=new AssemblyName("Alchemy.DynamicSpeaker");var ab=AssemblyBuilder.DefineDynamicAssembly(an,AssemblyBuilderAccess.Run);var mb=ab.DefineDynamicModule(an.Name!);var tb=mb.DefineType("AlchemyGeneratedSpeaker",TypeAttributes.Public|TypeAttributes.Sealed|TypeAttributes.Class);tb.AddInterfaceImplementation(typeof(ISpeaker));var authority=tb.DefineField("_authority",typeof(Thing),FieldAttributes.Private|FieldAttributes.InitOnly);var ctor=tb.DefineConstructor(MethodAttributes.Public,CallingConventions.Standard,new[]{typeof(Thing)});var il=ctor.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Call,typeof(object).GetConstructor(Type.EmptyTypes)!);il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ldarg_1);il.Emit(OpCodes.Stfld,authority);il.Emit(OpCodes.Ret);Forward(tb,authority,"Speak",typeof(string),Type.EmptyTypes);Forward(tb,authority,"ReplaceCSharp",typeof(long),new[]{typeof(string)});Forward(tb,authority,"InstallRexxBehaviour",typeof(long),Type.EmptyTypes);return tb.CreateType()!;}
 static void Forward(TypeBuilder tb,FieldBuilder field,string name,Type result,Type[] args){var target=typeof(Thing).GetMethod(name,BindingFlags.Instance|BindingFlags.Public,null,args,null)!;var m=tb.DefineMethod(name,MethodAttributes.Public|MethodAttributes.Virtual,result,args);var il=m.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ldfld,field);for(int i=0;i<args.Length;i++)il.Emit(OpCodes.Ldarg,i+1);il.Emit(OpCodes.Callvirt,target);il.Emit(OpCodes.Ret);if(name=="Speak")tb.DefineMethodOverride(m,typeof(ISpeaker).GetMethod(nameof(ISpeaker.Speak))!);}
 public static ISpeaker Create(Thing authority)=>(ISpeaker)Activator.CreateInstance(SpeakerType,authority)!;
}
class Program {
 // Keep qualification failures stable and machine-readable while allowing probes to be extracted from Main incrementally.
 static void Require(bool condition,int exitCode){if(!condition)Environment.Exit(exitCode);}

 // Proves that removing a Rexx interposition provider reveals the CLR behaviour current at removal time.
 static void QualifyOverrideRevealCurrent(OoRexxHost host){
  var target=new Thing();var handle=ClrObjectRegistry.Register(target);var generation1=target.ReplaceCSharp("C#-UNDER-OVERRIDE-1");
  using var probe=host.CallProgram("rexx/clr_override_reveal_current.rex",handle.ToString());
  Console.WriteLine($"override-reveal-current={probe}");
  Require(generation1==1&&probe.ToString()=="REXX-OVERRIDE|2|REXX-OVERRIDE|C#-UNDER-OVERRIDE-2|1",24);
  Console.WriteLine("REXX OVERRIDE REMOVAL REVEALS CURRENT CLR TARGET PASS");
 }


 // Proves Inspector remains a cooperative observer while CLR behaviour is replaced underneath it.
 static void QualifyInspectorLiveReplacement(OoRexxHost host){
  using(var inspectorWorker=host.CallProgram("rexx/live_behaviour_worker.rex","inspector-worker")){var inspected=new Thing{RexxPeer=inspectorWorker};var ig1=inspected.ReplaceCSharp("C#-INSPECTOR-1");var ih=ClrObjectRegistry.Register(inspected);using var ir=host.CallProgram("rexx/inspector_cooperative_clr.rex",ih.ToString());var parts=ir.ToString().Split('|');Console.WriteLine($"inspector-cooperative={ir}");if(parts.Length!=6||parts[0]!="1"||parts[1]!="2"||parts[2]!="C#-INSPECTOR-1"||parts[3]!="2"||parts[4]!="C#-INSPECTOR-2"||!int.TryParse(parts[5],out var events)||events<1||ig1!=1)Environment.Exit(22);Console.WriteLine("INSPECTOR V0.8.1 + CLR LIVE REPLACEMENT PASS");inspected.RexxPeer=null;}
 }

 // Holds generation 1 in-flight while Rexx and C# publish generations 2 and 3; the held call must retain its immutable snapshot.
 // Inspector is attached before the race and must remain a cooperative provider without changing CLR identity or emitted interface type.
 static void QualifyConcurrentGenerationSnapshot(OoRexxHost host){
  using(var concurrentWorker=host.CallProgram("rexx/live_behaviour_worker.rex","concurrent-worker")){var authority=new Thing{RexxPeer=concurrentWorker};ISpeaker speaker=TypedSpeakerFactory.Create(authority);object stable=speaker;var stableType=stable.GetType();var authorityHandle=ClrObjectRegistry.Register(authority);using(var setup=host.CallProgram("rexx/inspector_concurrent_clr.rex",authorityHandle.ToString())){Console.WriteLine($"concurrent-inspector-setup={setup}");if(setup.ToString()!="1|2")Environment.Exit(23);}using var entered=new ManualResetEventSlim(false);using var release=new ManualResetEventSlim(false);var g1=authority.InstallBlockingCSharp("C#-CONCURRENT-1",entered,release);var held=Task.Run(()=>authority.InvokeSnapshot());if(!entered.Wait(TimeSpan.FromSeconds(10)))Environment.Exit(19);using(var p=host.CallProgram("rexx/clr_roundtrip.rex",authorityHandle.ToString())){using var rg=p.Send("INSTALLREXXBEHAVIOUR");if(rg.ToString()!="2")Environment.Exit(20);}var g3=authority.ReplaceCSharp("C#-CONCURRENT-3");release.Set();var old=held.GetAwaiter().GetResult();var current=authority.InvokeSnapshot();Console.WriteLine($"concurrent-held={old.Value}|generation={old.Generation}");Console.WriteLine($"concurrent-current={current.Value}|generation={current.Generation}");Console.WriteLine($"concurrent-publications={g1}|2|{g3}");Console.WriteLine($"concurrent-interface-isa={speaker is ISpeaker}");Console.WriteLine($"concurrent-type-stable={ReferenceEquals(stableType,stable.GetType())}");if(old.Generation!=1||old.Value!="C#-CONCURRENT-1"||current.Generation!=3||current.Value!="C#-CONCURRENT-3"||g1!=1||g3!=3||speaker is not ISpeaker||!ReferenceEquals(stableType,stable.GetType()))Environment.Exit(21);authority.RexxPeer=null;Console.WriteLine("CONCURRENT REXX + C# GENERATION SNAPSHOT PASS");Console.WriteLine("INSPECTOR V0.8.1 REMAINED COOPERATIVELY ATTACHED DURING GENERATION RACE PASS");}
 }

 // Qualifies live C# -> Rexx -> C# behaviour publication on one stable CLR authority object.
 static void QualifyLiveBehaviour(OoRexxHost host,Thing original,ulong handle){
  using(var liveBehaviour=host.CallProgram("rexx/live_behaviour_worker.rex","worker")){original.RexxPeer=liveBehaviour;var g1=original.ReplaceCSharp("C#-LIVE-1");using var before=host.CallProgram("rexx/live_behaviour_observe.rex",handle.ToString());Console.WriteLine($"live-behaviour-before={before}|generation={g1}");if(before.ToString()!="C#-LIVE-1")Environment.Exit(14);using var install=host.CallProgram("rexx/live_behaviour_install.rex",handle.ToString());Console.WriteLine($"live-behaviour-rexx={install}|generation={original.BehaviourGeneration}");if(install.ToString()!="REXX-LIVE")Environment.Exit(15);var g3=original.ReplaceCSharp("C#-LIVE-2");using var after=host.CallProgram("rexx/live_behaviour_observe.rex",handle.ToString());Console.WriteLine($"live-behaviour-after={after}|generation={g3}");if(after.ToString()!="C#-LIVE-2")Environment.Exit(16);using var identityProxy=host.CallProgram("rexx/clr_roundtrip.rex",handle.ToString());using var identitySelf=identityProxy.Send("SELF");using var identityHandle=identitySelf.Send("ALCHEMYHANDLE");var ih=ulong.Parse(identityHandle.ToString());Console.WriteLine($"live-behaviour-identity={ReferenceEquals(original,ClrObjectRegistry.Resolve(ih))}");if(!ReferenceEquals(original,ClrObjectRegistry.Resolve(ih)))Environment.Exit(17);original.RexxPeer=null;Console.WriteLine("LIVE REXX + C# METHOD REPLACEMENT ON SAME CLR OBJECT PASS");}
  using(var typedWorker=host.CallProgram("rexx/live_behaviour_worker.rex","typed-worker")){var typedAuthority=new Thing{RexxPeer=typedWorker};ISpeaker speaker=TypedSpeakerFactory.Create(typedAuthority);object typedObject=speaker;var typedHandle=ClrObjectRegistry.Register(typedObject);var stableType=typedObject.GetType();var tg1=typedAuthority.ReplaceCSharp("C#-TYPED-1");var first=speaker.Speak();using var typedProxy=host.CallProgram("rexx/clr_roundtrip.rex",typedHandle.ToString());using var installTyped=typedProxy.Send("INSTALLREXXBEHAVIOUR");var second=speaker.Speak();var tg3=typedAuthority.ReplaceCSharp("C#-TYPED-2");var third=speaker.Speak();Console.WriteLine($"typed-interface-before={first}|generation={tg1}");Console.WriteLine($"typed-interface-rexx={second}|generation={installTyped}");Console.WriteLine($"typed-interface-after={third}|generation={tg3}");Console.WriteLine($"typed-interface-isa={speaker is ISpeaker}");Console.WriteLine($"typed-interface-identity={ReferenceEquals(typedObject,ClrObjectRegistry.Resolve(typedHandle))}");Console.WriteLine($"typed-interface-type-stable={ReferenceEquals(stableType,typedObject.GetType())}");if(first!="C#-TYPED-1"||second!="REXX-LIVE"||third!="C#-TYPED-2"||speaker is not ISpeaker||!ReferenceEquals(typedObject,ClrObjectRegistry.Resolve(typedHandle))||!ReferenceEquals(stableType,typedObject.GetType()))Environment.Exit(18);typedAuthority.RexxPeer=null;Console.WriteLine("TYPED CLR INTERFACE + LIVE REXX METHOD REPLACEMENT PASS");}
 }
 static void Main(){
 var original=new Thing(); var h=ClrObjectRegistry.Register(original); using var host=new OoRexxHost();
 using(var proxy=host.CallProgram("rexx/clr_roundtrip.rex",h.ToString())){using var ping=proxy.Send("PING");Console.WriteLine($"callback={ping}");using var isa=proxy.Send("DOTNETISA","IAlchemyMarker");Console.WriteLine($"interface={isa}");using var baseIsa=proxy.Send("DOTNETISA","BaseThing");Console.WriteLine($"base={baseIsa}");using var self=proxy.Send("SELF");using var rh=self.Send("ALCHEMYHANDLE");var returned=ulong.Parse(rh.ToString());Console.WriteLine($"identity={ReferenceEquals(original,ClrObjectRegistry.Resolve(returned))}");if(ping.ToString()!="pong-from-clr"||isa.ToString()!="1"||baseIsa.ToString()!="1"||!ReferenceEquals(original,ClrObjectRegistry.Resolve(returned)))Environment.Exit(1);}
 using(var args=host.CallProgram("rexx/clr_arguments.rex",h.ToString())){Console.WriteLine($"arguments={args}");if(args.ToString()!="OMITTED|NIL|EMPTY|VALUE:hello")Environment.Exit(3);Console.WriteLine("REXX -> CLR OMITTED != NIL != EMPTY PASS");}
 var other=new Thing();var oh=ClrObjectRegistry.Register(other);using(var echoed=host.CallProgram("rexx/clr_object_argument.rex",$"{h} {oh}")){using var eh=echoed.Send("ALCHEMYHANDLE");var ehandle=ulong.Parse(eh.ToString());Console.WriteLine($"foreign-object-arg-identity={ReferenceEquals(other,ClrObjectRegistry.Resolve(ehandle))}");if(!ReferenceEquals(other,ClrObjectRegistry.Resolve(ehandle)))Environment.Exit(4);}
 using(var proxy2=host.CallProgram("rexx/clr_roundtrip.rex",h.ToString())){using var fortyTwo=proxy2.Send("FORTYTWO");using var pi=proxy2.Send("PI");Console.WriteLine($"typed-returns={fortyTwo}|{pi}");if(fortyTwo.ToString()!="42"||pi.ToString()!="3.25")Environment.Exit(5);}
 using(var receiver=host.CallProgram("rexx/reverse_arguments.rex",h.ToString())){using var rev=receiver.SendSparse("SLOTS",AlchemyOmitted.Value,null,"","hello");Console.WriteLine($"clr-to-rexx-arguments={rev}");if(rev.ToString()!="OMITTED|NIL|EMPTY|hello")Environment.Exit(6);using var num=receiver.SendSparse("NUMERIC",41L,2.75);Console.WriteLine($"clr-to-rexx-numeric={num}");if(num.ToString()!="1|1|42|3.25")Environment.Exit(7);using var same=receiver.SendSparse("SAMEOBJECT",receiver);Console.WriteLine($"rexx-resident-self-identity={same}");if(same.ToString()!="1")Environment.Exit(8);using var echoedRexx=receiver.SendSparse("ECHOOBJECT",receiver);using var sameReturned=receiver.SendSparse("SAMEOBJECT",echoedRexx);Console.WriteLine($"rexx-resident-roundtrip-identity={sameReturned}");if(sameReturned.ToString()!="1")Environment.Exit(9);}
 using(var nestedPeer=host.CallProgram("rexx/reverse_arguments.rex",h.ToString())){original.RexxPeer=nestedPeer;using var nestedProxy=host.CallProgram("rexx/clr_roundtrip.rex",h.ToString());using var nestedResult=nestedProxy.Send("NESTEDSELF");using var nestedHandle=nestedResult.Send("ALCHEMYHANDLE");var nh=ulong.Parse(nestedHandle.ToString());Console.WriteLine("nested-reentrant-rexx-identity=1");Console.WriteLine($"nested-reentrant-clr-identity={ReferenceEquals(original,ClrObjectRegistry.Resolve(nh))}");if(!ReferenceEquals(original,ClrObjectRegistry.Resolve(nh)))Environment.Exit(10);original.RexxPeer=null;}
 QualifyLiveBehaviour(host,original,h);
 QualifyConcurrentGenerationSnapshot(host);
 QualifyInspectorLiveReplacement(host);
 QualifyOverrideRevealCurrent(host);
 using(var typeprobe=host.CallProgram("rexx/type_authority.rex",h.ToString())){Console.WriteLine($"clr-type-authority={typeprobe}");if(typeprobe.ToString()!="Thing|BaseThing|1|1|1|1")Environment.Exit(13);Console.WriteLine("CLR SYSTEM.TYPE AUTHORITY + IDENTITY PASS");}
 using(var exprobe=host.CallProgram("rexx/clr_exception.rex",h.ToString())){Console.WriteLine($"clr-exception-condition={exprobe}");if(!exprobe.ToString().Contains("DOTNET_EXCEPTION")||!exprobe.ToString().Contains("alchemy-clr-boom"))Environment.Exit(11);}
 using(var excollision=host.CallProgram("rexx/clr_exception_collision.rex",h.ToString())){Console.WriteLine($"clr-exception-no-fallback={excollision}");if(!excollision.ToString().Contains("DOTNET_EXCEPTION")||!excollision.ToString().Contains("alchemy-clr-boom")||excollision.ToString().Contains("ORIGINAL-UNKNOWN"))Environment.Exit(12);}
 using(var collision=host.CallProgram("rexx/clr_unknown_collision.rex",h.ToString())){using var known=collision.Send("KNOWN");using var projected=collision.Send("PING");using var fallback=collision.Send("SOMETHINGELSE");Console.WriteLine($"known-rexx-method={known}");Console.WriteLine($"projected-clr-method={projected}");Console.WriteLine($"post-projection-fallback={fallback}");if(known.ToString()!="REXX-KNOWN"||projected.ToString()!="pong-from-clr"||fallback.ToString()!="ORIGINAL-UNKNOWN:SOMETHINGELSE:0")Environment.Exit(2);Console.WriteLine("EXISTING UNKNOWN RELOCATION + CLR PROJECTION PASS");}
}}
