/* Wire3D browser renderer.
   Semantic/model/view mathematics are supplied by ooRexx Maths v0.8.
   The static browser route owns only viewport-dependent OpenGL projection. */
export function wire3dProjectionOpenGL(fovYDegrees, aspect, near, far) {
  if (!(aspect > 0 && near > 0 && far > near)) throw new Error('invalid Wire3D projection parameters');
  const f=1/Math.tan((fovYDegrees*Math.PI/180)/2);
  return [f/aspect,0,0,0, 0,f,0,0, 0,0,(far+near)/(near-far),-1, 0,0,(2*far*near)/(near-far),0];
}
export function wire3dTransformPoint(m,v) {
  return [
    m[0]*v[0]+m[4]*v[1]+m[8]*v[2]+m[12]*v[3],
    m[1]*v[0]+m[5]*v[1]+m[9]*v[2]+m[13]*v[3],
    m[2]*v[0]+m[6]*v[1]+m[10]*v[2]+m[14]*v[3],
    m[3]*v[0]+m[7]*v[1]+m[11]*v[2]+m[15]*v[3]
  ];
}
export function wire3dMultiply(a,b) {
  const out=new Array(16).fill(0);
  for(let c=0;c<4;c++) for(let r=0;r<4;r++) for(let k=0;k<4;k++) out[c*4+r]+=a[k*4+r]*b[c*4+k];
  return out;
}
export function wire3dPresentationNavigation(yaw=0,pitch=0,dolly=0) {
  const cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch);
  const ry=[cy,0,-sy,0, 0,1,0,0, sy,0,cy,0, 0,0,0,1];
  const rx=[1,0,0,0, 0,cx,sx,0, 0,-sx,cx,0, 0,0,0,1];
  const tz=[1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,dolly,1];
  return {world:wire3dMultiply(ry,rx), eye:tz};
}
export function wire3dProjectPoint(model,view,projection,point=[0,0,0,1]) {
  const world=wire3dTransformPoint(model,point), eye=wire3dTransformPoint(view,world), clip=wire3dTransformPoint(projection,eye);
  if (!Number.isFinite(clip[3]) || clip[3] <= 0) return null;
  return {x:clip[0]/clip[3],y:clip[1]/clip[3],z:clip[2]/clip[3],w:clip[3]};
}
export class Wire3DRenderer {
  constructor(canvas,info,detail=null,diagnostic=null,hud=null){this.canvas=canvas;this.info=info;this.detail=detail;this.diagnostic=diagnostic;this.hud=hud;this.gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});if(!this.gl)throw new Error('WebGL required');this.scene=null;this.selected=null;this.centres=[];this.nav={yaw:0,pitch:0,dolly:0};this.pointers=new Map();this._program();this._trackingProgram();this.edgeBuf=this.gl.createBuffer();this._input();this.resize();addEventListener('resize',()=>this.resize())}
  _shader(t,s){let gl=this.gl,x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(x));return x}
  _program(){const gl=this.gl,vs=`attribute vec3 p;uniform mat4 model;uniform mat4 view;uniform mat4 projection;void main(){gl_Position=projection*view*model*vec4(p,1.);}`,fs=`precision mediump float;uniform vec4 c;void main(){gl_FragColor=c;}`;this.prog=gl.createProgram();gl.attachShader(this.prog,this._shader(gl.VERTEX_SHADER,vs));gl.attachShader(this.prog,this._shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(this.prog);if(!gl.getProgramParameter(this.prog,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(this.prog));this.buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,-1,1,-1,-1,1,1,-1,-1,1,-1,-1,-1,1,1,-1,1,1,1,1,-1,1,1]),gl.STATIC_DRAW);this.idx=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.idx);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array([0,1,2,0,2,3,4,6,5,4,7,6,0,4,5,0,5,1,3,2,6,3,6,7,1,5,6,1,6,2,0,3,7,0,7,4]),gl.STATIC_DRAW)}
  setScene(s){if(s?.rendererContract?.mathAuthority!=='OOREXX_MATHS_V0.8')throw new Error('scene lacks Maths v0.8 renderer contract');if(!Array.isArray(s?.camera?.viewMatrix)||s.camera.viewMatrix.length!==16)throw new Error('scene lacks authoritative view matrix');for(const n of s.nodes||[])if(!Array.isArray(n.modelMatrix)||n.modelMatrix.length!==16)throw new Error(`node ${n.id} lacks authoritative model matrix`);this.scene=s;this.draw()}
  resize(){let d=devicePixelRatio||1,w=Math.max(1,this.canvas.clientWidth*d),h=Math.max(1,this.canvas.clientHeight*d);if(this.canvas.width!=w||this.canvas.height!=h){this.canvas.width=w;this.canvas.height=h}this.gl.viewport(0,0,w,h);this.draw()}
  _projection(){const c=this.scene.camera;return wire3dProjectionOpenGL(+c.fovYDegrees,this.canvas.width/this.canvas.height,+c.near,+c.far)}

  _trackingProgram(){const gl=this.gl,vs=`attribute vec2 p;attribute float size;varying float vSize;void main(){gl_Position=vec4(p,0.999,1.0);gl_PointSize=size;vSize=size;}`,fs=`precision mediump float;uniform float intensity;varying float vSize;void main(){vec2 q=gl_PointCoord-vec2(.5);if(vSize>1.5&&dot(q,q)>.22)discard;gl_FragColor=vec4(.32,.62,.68,intensity);}`;this.trackProg=gl.createProgram();gl.attachShader(this.trackProg,this._shader(gl.VERTEX_SHADER,vs));gl.attachShader(this.trackProg,this._shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(this.trackProg);this.trackBuf=gl.createBuffer()}
  _seed32(text){let h=2166136261>>>0;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return h||1}
  _trackingVertices(f){let state=this._seed32(`${f.version}|${f.seed}`);const rnd=()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return(state>>>0)/4294967296};let v=[];const add=(x,y,size=1)=>v.push(x,y,size);let major=Math.max(2,+f.majorDivisions||8),minor=Math.max(major,+f.minorDivisions||32);for(let i=1;i<major;i++){let x=-1+2*i/major;for(let j=0;j<=minor;j++)add(x,-1+2*j/minor,1);let y=-1+2*i/major;for(let j=0;j<=minor;j++)add(-1+2*j/minor,y,1)}for(let i=0;i<Math.max(16,+f.starCount||384);i++){let cell=i%major,row=Math.floor(i/major)%major;let x=-1+2*(cell+(0.12+0.76*rnd()))/major,y=-1+2*(row+(0.12+0.76*rnd()))/major;add(x,y,(i%17===0)?4:(i%5===0?2.5:1.5))}return new Float32Array(v)}
  _trackingLines(f){let v=[],m=Math.max(2,+f.majorDivisions||8),add=(x1,y1,x2,y2)=>v.push(x1,y1,1,x2,y2,1);for(let i=1;i<m;i++){let q=-1+2*i/m;add(q,-1,q,1);add(-1,q,1,q)}add(-1,-.72,1,.58);add(-.82,1,.67,-1);return new Float32Array(v)}
  _drawTrackingField(){const f=this.scene?.trackingField;if(!f?.enabled)return;const gl=this.gl,stars=this._trackingVertices(f),lines=this._trackingLines(f);gl.disable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(this.trackProg);gl.bindBuffer(gl.ARRAY_BUFFER,this.trackBuf);let stride=3*4,p=gl.getAttribLocation(this.trackProg,'p'),sz=gl.getAttribLocation(this.trackProg,'size');gl.enableVertexAttribArray(p);gl.enableVertexAttribArray(sz);gl.uniform1f(gl.getUniformLocation(this.trackProg,'intensity'),Math.max(.15,Math.min(.9,+f.intensity||.62)));gl.bufferData(gl.ARRAY_BUFFER,lines,gl.DYNAMIC_DRAW);gl.vertexAttribPointer(p,2,gl.FLOAT,false,stride,0);gl.vertexAttribPointer(sz,1,gl.FLOAT,false,stride,8);gl.drawArrays(gl.LINES,0,lines.length/3);gl.bufferData(gl.ARRAY_BUFFER,stars,gl.DYNAMIC_DRAW);gl.vertexAttribPointer(p,2,gl.FLOAT,false,stride,0);gl.vertexAttribPointer(sz,1,gl.FLOAT,false,stride,8);gl.drawArrays(gl.POINTS,0,stars.length/3);gl.disable(gl.BLEND);gl.enable(gl.DEPTH_TEST)}
  _input(){
    let drag=null,pinch=null;
    const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
    this.canvas.addEventListener('pointerdown',e=>{this.canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===1)drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};if(this.pointers.size===2){const a=[...this.pointers.values()];pinch=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)} });
    this.canvas.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;const old=this.pointers.get(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===2){const a=[...this.pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch){this.nav.dolly=clamp(this.nav.dolly+(d-pinch)*.012,-8,8);this.draw()}pinch=d;drag=null;return}if(drag&&drag.id===e.pointerId){const dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.abs(dx)+Math.abs(dy)>1)drag.moved=true;this.nav.yaw+=dx*.008;this.nav.pitch=clamp(this.nav.pitch+dy*.008,-1.2,1.2);this.draw()}});
    this.canvas.addEventListener('pointerup',e=>{const was=drag&&drag.id===e.pointerId&&!drag.moved;this.pointers.delete(e.pointerId);if(was)this.pick(e.clientX,e.clientY);drag=null;pinch=null});
    this.canvas.addEventListener('pointercancel',e=>{this.pointers.delete(e.pointerId);drag=null;pinch=null});
    this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.nav.dolly=clamp(this.nav.dolly-e.deltaY*.008,-8,8);this.draw()},{passive:false});
    addEventListener('keydown',e=>{if(e.target&&/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;let used=true;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')this.nav.yaw-=.12;else if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')this.nav.yaw+=.12;else if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')this.nav.dolly=clamp(this.nav.dolly+.5,-8,8);else if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')this.nav.dolly=clamp(this.nav.dolly-.5,-8,8);else if(e.key.toLowerCase()==='q')this.nav.pitch=clamp(this.nav.pitch-.1,-1.2,1.2);else if(e.key.toLowerCase()==='e')this.nav.pitch=clamp(this.nav.pitch+.1,-1.2,1.2);else if(e.key.toLowerCase()==='r'||e.key.toLowerCase()==='h')this.resetNavigation();else if(e.key==='Tab'){e.preventDefault();this.selectRelative(e.shiftKey?-1:1);return}else if(e.key.toLowerCase()==='f'){this.frameSelected();return}else used=false;if(used){e.preventDefault();this.draw()}});
    if(this.hud){this.hud.querySelector('[data-nav=home]')?.addEventListener('click',()=>this.resetNavigation());this.hud.querySelector('[data-nav=prev]')?.addEventListener('click',()=>this.selectRelative(-1));this.hud.querySelector('[data-nav=next]')?.addEventListener('click',()=>this.selectRelative(1));this.hud.querySelector('[data-nav=frame]')?.addEventListener('click',()=>this.frameSelected());this.hud.querySelector('[data-nav=workspace]')?.addEventListener('click',()=>this.openPresentation())}
  }
  resetNavigation(){this.nav={yaw:0,pitch:0,dolly:0};this.draw()}
  selectRelative(step){if(!this.scene?.nodes?.length)return;let i=this.selected?this.scene.nodes.indexOf(this.selected):-1;i=(i+step+this.scene.nodes.length)%this.scene.nodes.length;this.selected=this.scene.nodes[i];this._showSelection(this.selected);this.draw()}
  frameSelected(){if(!this.selected)return;this.nav.dolly=3;this.draw()}
  _presentationView(){const n=wire3dPresentationNavigation(this.nav.yaw,this.nav.pitch,this.nav.dolly);return wire3dMultiply(n.eye,wire3dMultiply(this.scene.camera.viewMatrix,n.world))}
  _screen(model,view,projection){const p=wire3dProjectPoint(model,view,projection);if(!p)return null;let r=this.canvas.getBoundingClientRect();return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2,ndc:p}}
  pick(x,y){let best=null,bd=Infinity;for(let c of this.centres){let d=Math.hypot(c.x-x,c.y-y);if(d<bd){bd=d;best=c}}if(best&&bd<70){this.selected=best.node;this._showSelection(best.node);this.canvas.dispatchEvent(new CustomEvent('wire3d-select',{detail:{id:best.node.id,semanticRef:best.node.semanticRef,node:best.node}}));this.draw()}}
  _showSelection(n){
    if(!this.detail)return; const meta=n.metadata||{},card=meta.card;
    if(card?.kind==='person'){
      const details=Object.entries(card.details||{}).map(([k,v])=>`<div class="kv"><b>${this._esc(k)}</b><span>${this._esc(v)}</span></div>`).join('');
      const links=(card.links||[]).map(l=>`<button class="link" data-target="${this._esc(l.targetId)}"><span>→ ${this._esc(l.label)}</span><small>${this._esc(l.relation)} / ${this._esc(l.confidence||'')}</small></button>`).join('');
      const media=(card.media||[]).map(m=>`<button class="media" data-media="${this._esc(m.src)}">▣ ${this._esc(m.label||m.type)}</button>`).join('');
      const map=this.scene?.mapContext;const mapView=map?.embedUrl?`<div class="section">GEOGRAPHIC CONTEXT</div><div class="mapElement"><iframe title="OpenStreetMap geographic context" loading="lazy" src="${this._esc(map.embedUrl)}"></iframe><div class="mapFoot"><span>${this._esc(map.latitude)}, ${this._esc(map.longitude)}</span><a href="${this._esc(map.licenseUrl||map.url)}" target="wire3d-map">${this._esc(map.attribution||'OpenStreetMap')}</a><button class="media mapContext">ENTER MAP</button></div></div>`:'';this.detail.innerHTML=`<div class="cardhead"><img src="${this._esc(card.headshot||'')}" alt="Demonstration headshot"><div><strong>${this._esc(card.title||n.id)}</strong><small>${this._esc(card.subtitle||n.semanticRef||'')}</small></div></div><div class="facts">${details}</div><div class="section">RELATIONSHIPS</div><div class="links">${links||'<em>NONE PROJECTED</em>'}</div><div class="section">MEDIA</div><div class="mediaRow">${media||'<em>NONE</em>'}</div>${mapView}`;
      this.detail.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>this.selectById(b.dataset.target)));
      this.detail.querySelectorAll('[data-media]').forEach(b=>b.addEventListener('click',()=>this.openMedia(b.dataset.media,card.title)));this.detail.querySelector('.mapContext')?.addEventListener('click',()=>window.open(this.scene.mapContext.url,'wire3d-map'));
    } else {
      let rows=Object.entries(meta).filter(([k])=>k!=='projectionState'&&k!=='card').slice(0,8).map(([k,v])=>`<div><b>${this._esc(k)}</b> ${this._esc(typeof v==='object'?JSON.stringify(v):v)}</div>`).join('');
      this.detail.innerHTML=`<strong>${this._esc(n.representation?.label||n.id)}</strong><small>${this._esc(n.semanticRef||'NO SEMANTIC REFERENCE')}</small>${rows}`;
    }
    this.detail.hidden=false
  }
  selectById(id){const n=this.scene?.nodes?.find(x=>x.id===id);if(!n)return;this.selected=n;this._showSelection(n);this.draw()}
  openPresentation(){
    const p=this.scene?.presentationWorkspace;if(!p)return;
    let o=document.querySelector('#presentationOverlay');if(o)o.remove();o=document.createElement('div');o.id='presentationOverlay';
    const media=(p.media||[]).map(m=>m.mediaType==='video'?`<video controls src="${this._esc(m.src)}"></video>`:m.mediaType==='audio'?`<audio controls src="${this._esc(m.src)}"></audio>`:`<a href="${this._esc(m.src)}">MEDIA</a>`).join('');
    const transcripts=(p.transcripts||[]).map(t=>{const speakers=(t.speakers||[]).map(sp=>`<button class="pspeaker" data-person-label="${this._esc(sp.label)}"><img src="${this._esc(sp.headshot||'')}" alt="Demonstration headshot"><b>${this._esc(sp.label)}</b><small>${this._esc(sp.displayName||'')}</small></button>`).join('');return `<div class="pbody"><div class="pspeakers">${speakers}</div><div class="ptranscript">${this._esc(t.text||'')}</div></div>`}).join('');
    o.innerHTML=`<button class="pclose">CLOSE</button><strong>${this._esc(p.title||p.layout)}</strong><small>${this._esc(p.layout||'')}</small><div class="pmedia">${media}</div>${transcripts}`;document.body.append(o);o.querySelector('.pclose').onclick=()=>o.remove();
    o.querySelectorAll('[data-person-label]').forEach((b,i)=>b.onclick=()=>{const target=(this.scene?.nodes||[]).find(n=>n.metadata?.card?.headshot===b.querySelector('img')?.getAttribute('src'));if(target){o.remove();this.selectById(target.id)}})
  }
  openMedia(src,title='MEDIA'){let o=document.querySelector('#mediaOverlay');if(!o){o=document.createElement('div');o.id='mediaOverlay';o.innerHTML='<button class="close">CLOSE</button><div class="mediaTitle"></div><img>';document.body.append(o);o.querySelector('.close').onclick=()=>o.remove()}o.querySelector('.mediaTitle').textContent=title+' / MEDIA';o.querySelector('img').src=src}
  _drawEdges(view,projection){const gl=this.gl,byId=new Map((this.scene?.nodes||[]).map(n=>[n.id,n]));let a=[];for(const e of this.scene?.edges||[]){const s=byId.get(e.sourceId),t=byId.get(e.targetId);if(!s||!t)continue;a.push(s.modelMatrix[12],s.modelMatrix[13],s.modelMatrix[14],t.modelMatrix[12],t.modelMatrix[13],t.modelMatrix[14])}if(!a.length)return;gl.useProgram(this.prog);gl.bindBuffer(gl.ARRAY_BUFFER,this.edgeBuf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.DYNAMIC_DRAW);let p=gl.getAttribLocation(this.prog,'p');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,3,gl.FLOAT,false,0,0);const I=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];gl.uniformMatrix4fv(gl.getUniformLocation(this.prog,'model'),false,new Float32Array(I));gl.uniformMatrix4fv(gl.getUniformLocation(this.prog,'view'),false,new Float32Array(view));gl.uniformMatrix4fv(gl.getUniformLocation(this.prog,'projection'),false,new Float32Array(projection));gl.uniform4fv(gl.getUniformLocation(this.prog,'c'),[.28,.68,.72,.72]);gl.lineWidth(1);gl.drawArrays(gl.LINES,0,a.length/3)}
  _esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  draw(){if(!this.scene)return;const gl=this.gl,view=this._presentationView(),projection=this._projection();gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.clearColor(.018,.025,.03,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this._drawTrackingField();this._drawEdges(view,projection);gl.useProgram(this.prog);gl.bindBuffer(gl.ARRAY_BUFFER,this.buf);let p=gl.getAttribLocation(this.prog,'p');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.idx);gl.uniformMatrix4fv(gl.getUniformLocation(this.prog,'view'),false,new Float32Array(view));gl.uniformMatrix4fv(gl.getUniformLocation(this.prog,'projection'),false,new Float32Array(projection));this.centres=[];let visible=0;for(const n of this.scene.nodes||[]){if(n.representation?.kind==='application')continue;const model=n.modelMatrix,sc=this._screen(model,view,projection);if(sc&&Math.abs(sc.ndc.x)<=1&&Math.abs(sc.ndc.y)<=1&&sc.ndc.z>=-1&&sc.ndc.z<=1){this.centres.push({...sc,node:n});visible++}gl.uniformMatrix4fv(gl.getUniformLocation(this.prog,'model'),false,new Float32Array(model));let cls=n.representation.classification,col=n===this.selected?[.62,.68,.56,1]:cls==='ai-service'?[.15,.42,.48,1]:cls==='infrastructure'?[.22,.28,.31,1]:[.32,.35,.36,1];gl.uniform4fv(gl.getUniformLocation(this.prog,'c'),col);gl.drawElements(gl.TRIANGLES,36,gl.UNSIGNED_SHORT,0)}const err=gl.getError();this.info.textContent=`${this.scene.title} / REV ${this.scene.revision} / ${(this.scene.nodes||[]).filter(n=>n.representation?.kind!=='application').length} OBJECTS / ${visible} IN FRAME / FIELD ${this.scene?.trackingField?.enabled?'ON':'OFF'} / GL ${err===gl.NO_ERROR?'OK':'ERR '+err}`;this._diagnose(view,projection,err)}
  _diagnose(view,projection,glError){if(!this.diagnostic)return;const gl=this.gl,r=this.canvas.getBoundingClientRect(),d=this.canvas.width/Math.max(1,r.width);let lines=[];let painted=0;for(const c of this.centres){const px=Math.max(0,Math.min(this.canvas.width-1,Math.round((c.x-r.left)*d))),py=Math.max(0,Math.min(this.canvas.height-1,Math.round((r.bottom-c.y)*d)));const rgba=new Uint8Array(4);gl.readPixels(px,py,1,1,gl.RGBA,gl.UNSIGNED_BYTE,rgba);const bg=rgba[0]<12&&rgba[1]<16&&rgba[2]<20;if(!bg)painted++;lines.push(`${c.node.id}  NDC ${c.ndc.x.toFixed(3)}, ${c.ndc.y.toFixed(3)}, ${c.ndc.z.toFixed(3)}  PIXEL ${[...rgba].join(',')}`)}const ext=gl.getExtension('WEBGL_debug_renderer_info');const renderer=ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);this.diagnostic.textContent=`MATH OOREXX_MATHS_V0.8 / OPENGL\nVIEWPORT ${this.canvas.width}x${this.canvas.height} / ${this.centres.length} CLIPPED-IN / ${painted} PAINTED\nWEBGL ${renderer} / ERROR ${glError}\n${lines.join('\n')}`;this.diagnostic.dataset.pass=(glError===gl.NO_ERROR&&this.centres.length>0&&painted===this.centres.length)?'true':'false'}
}
