#include "wire_ui_loader.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define MAX_NODE 256
#define MAX_LINE 2048
#define MAX_ATTR 24
typedef struct { char k[64],v[512]; } Attr;
typedef struct { int depth; WireHandle h; } Parent;
static WireElementKind kind(const char*s){if(!strcmp(s,"Window"))return WIRE_WINDOW;if(!strcmp(s,"Stack"))return WIRE_STACK;if(!strcmp(s,"Split"))return WIRE_SPLIT;if(!strcmp(s,"Label"))return WIRE_LABEL;if(!strcmp(s,"Button"))return WIRE_BUTTON;if(!strcmp(s,"TextInput"))return WIRE_TEXT_INPUT;if(!strcmp(s,"Scroll"))return WIRE_SCROLL;if(!strcmp(s,"VirtualList"))return WIRE_VIRTUAL_LIST;if(!strcmp(s,"Document"))return WIRE_DOCUMENT;return 0;}
static const WireListSource* source(const WireUILoadContext*c,const char*n){for(size_t i=0;i<c->list_count;i++)if(!strcmp(c->lists[i].name,n))return c->lists[i].source;return NULL;}
static const char* av(Attr*a,int n,const char*k){for(int i=0;i<n;i++)if(!strcmp(a[i].k,k))return a[i].v;return NULL;}
static int attrs(const char*p,Attr*a){int n=0;while(*p&&n<MAX_ATTR){while(isspace((unsigned char)*p)||*p=='/')p++;if(!*p||*p=='>')break;const char*k=p;while(*p&&!isspace((unsigned char)*p)&&*p!='='&&*p!='>')p++;size_t kn=(size_t)(p-k);if(kn>=sizeof a[n].k)kn=sizeof a[n].k-1;memcpy(a[n].k,k,kn);a[n].k[kn]=0;while(isspace((unsigned char)*p))p++;if(*p=='=')p++;while(isspace((unsigned char)*p))p++;char q=0;if(*p=='"'||*p=='\'')q=*p++;const char*v=p;if(q){while(*p&&*p!=q)p++;}else while(*p&&!isspace((unsigned char)*p)&&*p!='>')p++;size_t vn=(size_t)(p-v);if(vn>=sizeof a[n].v)vn=sizeof a[n].v-1;memcpy(a[n].v,v,vn);a[n].v[vn]=0;if(q&&*p==q)p++;n++;}return n;}
static WireResult node(const WireUILoadContext*c,const char*t,Attr*a,int n,WireHandle parent,WireHandle*hnext,WireHandle*hout){WireElementKind k=kind(t);if(!k)return WIRE_EINVAL;WireHandle h=(*hnext)++;WireResult r=c->renderer->v->create(c->renderer,h,k,parent);if(r)return r;const char*id=av(a,n,"id");if(id){WireProperty p={"id",id};if((r=c->renderer->v->set_property(c->renderer,h,&p)))return r;if(c->element_loaded)c->element_loaded(c->element_loaded_ctx,id,h,k);}for(int i=0;i<n;i++){if(!strcmp(a[i].k,"id")||!strcmp(a[i].k,"source")||!strcmp(a[i].k,"start")||!strcmp(a[i].k,"count"))continue;WireProperty p={a[i].k,a[i].v};r=c->renderer->v->set_property(c->renderer,h,&p);if(r==WIRE_ENOTSUP)continue;if(r)return r;}if(k==WIRE_VIRTUAL_LIST){const char*sn=av(a,n,"source");const WireListSource*s=sn?source(c,sn):NULL;if(!s)return WIRE_ESTATE;if((r=c->renderer->v->bind_list(c->renderer,h,s)))return r;uint64_t st=av(a,n,"start")?strtoull(av(a,n,"start"),0,10):0;size_t ct=av(a,n,"count")?(size_t)strtoull(av(a,n,"count"),0,10):100;if((r=c->renderer->v->show_list_range(c->renderer,h,st,ct)))return r;}*hout=h;return WIRE_OK;}
static WireResult load_wire(FILE*f,const WireUILoadContext*c,WireHandle*out){char line[MAX_LINE];Parent st[64];int sp=0;WireHandle next=1,root=0;while(fgets(line,sizeof line,f)){char*p=line;int spaces=0;while(*p==' '){spaces++;p++;}if(*p=='#'||*p=='\n'||!*p)continue;int depth=spaces/2;char type[64];int z=0;while(*p&&!isspace((unsigned char)*p)&&z<63)type[z++]=*p++;type[z]=0;while(isspace((unsigned char)*p))p++;char id[128];z=0;while(*p&&!isspace((unsigned char)*p)&&z<127)id[z++]=*p++;id[z]=0;Attr a[MAX_ATTR];int n=attrs(p,a);if(*id&&n<MAX_ATTR){memmove(a+1,a,(size_t)n*sizeof *a);strcpy(a[0].k,"id");strncpy(a[0].v,id,sizeof a[0].v-1);a[0].v[sizeof a[0].v-1]=0;n++;}while(sp&&st[sp-1].depth>=depth)sp--;WireHandle parent=sp?st[sp-1].h:0,h=0;WireResult r=node(c,type,a,n,parent,&next,&h);if(r)return r;if(!root)root=h;st[sp++]=(Parent){depth,h};}*out=root;return root?WIRE_OK:WIRE_EINVAL;}
static WireResult load_xml(FILE*f,const WireUILoadContext*c,WireHandle*out){char *buf=NULL;size_t len=0;char tmp[MAX_LINE];while(fgets(tmp,sizeof tmp,f)){size_t n=strlen(tmp);char*nb=realloc(buf,len+n+1);if(!nb){free(buf);return WIRE_ESTATE;}buf=nb;memcpy(buf+len,tmp,n);len+=n;buf[len]=0;}Parent st[64];int sp=0;WireHandle next=1,root=0;for(char*p=buf;p&&*p;){char*lt=strchr(p,'<');if(!lt)break;char*gt=strchr(lt,'>');if(!gt)break;*gt=0;if(lt[1]=='?'||lt[1]=='!'){p=gt+1;continue;}if(lt[1]=='/'){if(sp)sp--;p=gt+1;continue;}char*q=lt+1;while(isspace((unsigned char)*q))q++;char type[64];int z=0;while(*q&&!isspace((unsigned char)*q)&&*q!='/'&&z<63)type[z++]=*q++;type[z]=0;if(!strcmp(type,"wire")){if(gt[-1]!='/')st[sp++]=(Parent){-1,0};p=gt+1;continue;}Attr a[MAX_ATTR];int n=attrs(q,a);WireHandle parent=sp?st[sp-1].h:0,h=0;WireResult r=node(c,type,a,n,parent,&next,&h);if(r){free(buf);return r;}if(!root)root=h;if(gt[-1]!='/')st[sp++]=(Parent){sp,h};p=gt+1;}free(buf);*out=root;return root?WIRE_OK:WIRE_EINVAL;}
WireResult wire_ui_load_file(const char*path,const WireUILoadContext*c,WireHandle*out){if(!path||!c||!c->renderer||!out)return WIRE_EINVAL;FILE*f=fopen(path,"rb");if(!f)return WIRE_ESTATE;const char*dot=strrchr(path,'.');WireResult r=(dot&&!strcmp(dot,".xml"))?load_xml(f,c,out):load_wire(f,c,out);fclose(f);return r;}
